/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/low_poly_cat.glb 
Author: volkanongun (https://sketchfab.com/volkanongun)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/low-poly-cat-1e7143dfafd04ff4891efcb06949a0b4
Title: Low Poly Cat
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/low_poly_cat.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.CatMesh2_lambert1_0.geometry} material={materials.lambert1} />
    </group>
  )
}

useGLTF.preload('/low_poly_cat.glb')
