/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/acoustic_guitar.glb 
*/

import React, { useRef, useEffect } from 'react'
import { useGLTF, PositionalAudio } from '@react-three/drei'

export function Acoustic_guitar(props) {
  const { nodes, materials } = useGLTF('/acoustic_guitar.glb')

  const sound = useRef()

  const playSound = () => {
    // Check if sound exists
    if (sound.current) {
        // Optional: Stop if already playing so you can spam-click it
        if (sound.current.isPlaying) sound.current.stop()
        
        // Play the sound!
        sound.current.play()
        
        // OPTIONAL: Add a little "wobble" animation or particle effect here later
    }
  }

  return (
    <group {...props} dispose={null}
      onClick={playSound}
      onPointerOver={() => document.body.style.cursor = 'pointer'}
      onPointerOut={() => document.body.style.cursor = 'auto'}
    >

      {/* 2. The Invisible Speaker 
          url: Path to your mp3 in the public folder
          distance: How far (in units) the sound carries. 
                    10 means it gets quiet 10 units away.
      */}
      <PositionalAudio 
        ref={sound} 
        url="/Guitar_Twang.mp3" 
        distance={5} 
        loop={false}
      />


      <mesh geometry={nodes.Circle031.geometry} material={materials['madreperla tastini']} position={[0, 0.009, -0.21]} rotation={[0.009, 0, 0]} />
      <mesh geometry={nodes.Circle030.geometry} material={materials['madreperla tastini']} position={[0, 0.009, -0.156]} rotation={[0.009, 0, 0]} />
      <mesh geometry={nodes.Circle029.geometry} material={materials['madreperla tastini']} position={[0, 0.008, -0.107]} rotation={[0.009, 0, 0]} />
      <mesh geometry={nodes.Circle023.geometry} material={materials['madreperla tastini']} position={[0, 0.007, 0.007]} rotation={[0.009, 0, 0]} />
      <group position={[-0.005, 0.009, 0.291]} rotation={[0.009, 0, 0]}>
        <mesh geometry={nodes.Circle042.geometry} material={materials['corde zigrinate']} />
        <mesh geometry={nodes.Circle042_1.geometry} material={materials['corde non zigrinate']} />
      </group>
      <group position={[-0.023, -0.002, -0.437]} rotation={[-0.212, -0.685, 0]}>
        <mesh geometry={nodes.Circle030_1.geometry} material={materials['corde zigrinate']} />
        <mesh geometry={nodes.Circle030_2.geometry} material={materials['corde non zigrinate']} />
      </group>
      <mesh geometry={nodes.corda_mi_cantino.geometry} material={materials['corde non zigrinate']} position={[0.02, 0.013, -0.36]} rotation={[0.009, 0, 0]} />
      <mesh geometry={nodes.corda_si.geometry} material={materials['corde non zigrinate']} position={[0.012, 0.013, -0.36]} rotation={[0.009, 0, 0]} />
      <group position={[0.004, 0.013, -0.36]} rotation={[0.009, 0, 0]}>
        <mesh geometry={nodes.Circle022_1.geometry} material={materials['corde zigrinate']} />
        <mesh geometry={nodes.Circle022_2.geometry} material={materials['corde non zigrinate']} />
      </group>
      <mesh geometry={nodes.ponticello.geometry} material={materials['capotasto e ponticelli']} position={[0, 0.008, -0.359]} rotation={[0.009, 0, 0]} />
      <mesh geometry={nodes.corda_mi_basso.geometry} material={materials['corde zigrinate']} position={[-0.025, 0.004, -0.403]} rotation={[-0.212, 0.813, 0]} />
      <mesh geometry={nodes.Circle022.geometry} material={materials['metallo meccaniche']} position={[0.022, -0.033, -0.458]} rotation={[2.929, 0.248, 0]} />
      <mesh geometry={nodes.Circle021.geometry} material={materials['metallo meccaniche']} position={[0.024, -0.026, -0.424]} rotation={[2.929, -0.651, 0]} />
      <mesh geometry={nodes.Circle020.geometry} material={materials['metallo meccaniche']} position={[0.025, -0.018, -0.39]} rotation={[2.929, 0, 0]} />
      <mesh geometry={nodes.chiave_sol.geometry} material={materials['metallo meccaniche']} position={[0.029, -0.037, -0.474]} rotation={[0.626, -0.054, 0.038]} />
      <mesh geometry={nodes.chiave_si.geometry} material={materials['metallo meccaniche']} position={[0.031, -0.03, -0.439]} rotation={[-0.539, -0.056, -0.034]} />
      <mesh geometry={nodes.chiave_mi_cantino.geometry} material={materials['metallo meccaniche']} position={[0.033, -0.022, -0.405]} rotation={[0.126, -0.065, 0.008]} />
      <mesh geometry={nodes.perno_sol.geometry} material={materials['metallo meccaniche']} position={[0.021, -0.014, -0.471]} rotation={[-0.212, -0.452, 0.001]} />
      <mesh geometry={nodes.perno_si.geometry} material={materials['metallo meccaniche']} position={[0.023, -0.006, -0.436]} rotation={[2.933, 1.255, 3.138]} />
      <mesh geometry={nodes.perno_mi_cantino.geometry} material={materials['metallo meccaniche']} position={[0.025, 0.001, -0.403]} rotation={[-0.212, 0.412, 0.001]} />
      <mesh geometry={nodes.jack.geometry} material={materials['metallo meccaniche']} position={[0, -0.05, 0.518]} rotation={[1.58, 0, 0]} />
      <mesh geometry={nodes.vite_reggicinghia.geometry} material={materials['metallo meccaniche']} position={[0, -0.099, -0.008]} rotation={[-3.132, 0, 0]} />
      <mesh geometry={nodes.reggicinghia.geometry} material={materials['metallo meccaniche']} position={[0, -0.099, -0.008]} rotation={[0.009, 0, 0]} />
      <mesh geometry={nodes.pirioli.geometry} material={materials['pirioli ponte']} position={[-0.024, 0.011, 0.306]} rotation={[-3.132, 0, -Math.PI]} />
      <mesh geometry={nodes.reggiponte.geometry} material={materials['legno reggiponte']} position={[0, 0.002, 0.296]} rotation={[0.009, 0, 0]} />
      <mesh geometry={nodes.Plane021.geometry} material={materials.frets} position={[0, 0.006, 0.083]} rotation={[1.58, 0, Math.PI / 2]} scale={[1, 1.001, 1]} />
      <mesh geometry={nodes.Plane020.geometry} material={materials.frets} position={[0, 0.006, 0.07]} rotation={[1.58, 0, Math.PI / 2]} scale={[1, 1.001, 1]} />
      <mesh geometry={nodes.Plane019.geometry} material={materials.frets} position={[0, 0.007, 0.058]} rotation={[1.58, 0, Math.PI / 2]} scale={[1, 1.001, 1]} />
      <mesh geometry={nodes.Plane018.geometry} material={materials.frets} position={[0, 0.007, 0.044]} rotation={[1.58, 0, Math.PI / 2]} scale={[1, 1.001, 1]} />
      <mesh geometry={nodes.Plane017.geometry} material={materials.frets} position={[0, 0.007, 0.03]} rotation={[1.58, 0, Math.PI / 2]} scale={[1, 1.001, 1]} />
      <mesh geometry={nodes.Plane016.geometry} material={materials.frets} position={[0, 0.007, 0.015]} rotation={[1.58, 0, Math.PI / 2]} scale={[1, 1.001, 1]} />
      <mesh geometry={nodes.Plane015.geometry} material={materials.frets} position={[0, 0.007, 0]} rotation={[1.58, 0, Math.PI / 2]} scale={[1, 1.001, 1]} />
      <mesh geometry={nodes.Plane014.geometry} material={materials.frets} position={[0, 0.007, -0.018]} rotation={[1.58, 0, Math.PI / 2]} scale={[1, 1.001, 1]} />
      <mesh geometry={nodes.Plane013.geometry} material={materials.frets} position={[0, 0.007, -0.035]} rotation={[1.58, 0, Math.PI / 2]} scale={[1, 1.001, 1]} />
      <mesh geometry={nodes.Plane012.geometry} material={materials.frets} position={[0, 0.008, -0.054]} rotation={[1.58, 0, Math.PI / 2]} scale={[1, 1.001, 1]} />
      <mesh geometry={nodes.Plane011.geometry} material={materials.frets} position={[0, 0.008, -0.075]} rotation={[1.58, 0, Math.PI / 2]} scale={[1, 1.001, 1]} />
      <mesh geometry={nodes.Plane010.geometry} material={materials.frets} position={[0, 0.008, -0.096]} rotation={[1.58, 0, Math.PI / 2]} scale={[1, 1.001, 1]} />
      <mesh geometry={nodes.Plane009.geometry} material={materials.frets} position={[0, 0.008, -0.119]} rotation={[1.58, 0, Math.PI / 2]} scale={[1, 1.001, 1]} />
      <mesh geometry={nodes.Plane008.geometry} material={materials.frets} position={[0, 0.008, -0.143]} rotation={[1.58, 0, Math.PI / 2]} scale={[1, 1.001, 1]} />
      <mesh geometry={nodes.Plane007.geometry} material={materials.frets} position={[0, 0.009, -0.169]} rotation={[1.58, 0, Math.PI / 2]} scale={[1, 1.001, 1]} />
      <mesh geometry={nodes.Plane006.geometry} material={materials.frets} position={[0, 0.009, -0.196]} rotation={[1.58, 0, Math.PI / 2]} scale={[1, 1.001, 1]} />
      <mesh geometry={nodes.Plane005.geometry} material={materials.frets} position={[0, 0.009, -0.225]} rotation={[1.58, 0, Math.PI / 2]} scale={[1, 1.001, 1]} />
      <mesh geometry={nodes.Plane004.geometry} material={materials.frets} position={[0, 0.009, -0.255]} rotation={[1.58, 0, Math.PI / 2]} scale={[1, 1.001, 1]} />
      <mesh geometry={nodes.Plane003.geometry} material={materials.frets} position={[0, 0.01, -0.288]} rotation={[1.58, 0, Math.PI / 2]} scale={[1, 1.001, 1]} />
      <mesh geometry={nodes.Plane002.geometry} material={materials.frets} position={[0, 0.01, -0.322]} rotation={[1.58, 0, Math.PI / 2]} scale={[1, 1.001, 1]} />
      <mesh geometry={nodes.manico.geometry} material={materials['legno manico']} position={[0, 0.005, 0.001]} rotation={[1.58, 0, Math.PI]} />
      <mesh geometry={nodes.Circle011.geometry} material={materials['metallo meccaniche']} position={[-0.022, -0.033, -0.458]} rotation={[2.929, -0.686, 0]} />
      <mesh geometry={nodes.Circle007.geometry} material={materials['metallo meccaniche']} position={[-0.024, -0.025, -0.424]} rotation={[2.929, -1.158, 0]} />
      <mesh geometry={nodes.Circle006.geometry} material={materials['metallo meccaniche']} position={[-0.025, -0.018, -0.39]} rotation={[2.929, -0.565, 0]} />
      <mesh geometry={nodes.chiave_re.geometry} material={materials['metallo meccaniche']} position={[-0.04, -0.037, -0.474]} rotation={[-0.996, -0.035, -0.056]} />
      <mesh geometry={nodes.chiave_la.geometry} material={materials['metallo meccaniche']} position={[-0.043, -0.03, -0.44]} rotation={[-0.731, -0.049, -0.044]} />
      <mesh geometry={nodes.chiave_mi_basso.geometry} material={materials['metallo meccaniche']} position={[-0.045, -0.022, -0.406]} rotation={[0.653, -0.053, 0.039]} />
      <mesh geometry={nodes.Circle014.geometry} material={materials['metallo meccaniche']} position={[-0.025, -0.018, -0.398]} rotation={[-0.213, -0.101, 3.119]} scale={0.215} />
      <mesh geometry={nodes.Circle015.geometry} material={materials['metallo meccaniche']} position={[-0.023, -0.026, -0.432]} rotation={[-0.213, -0.101, 3.119]} scale={0.215} />
      <mesh geometry={nodes.Circle016.geometry} material={materials['metallo meccaniche']} position={[-0.021, -0.033, -0.467]} rotation={[-0.213, -0.101, 3.119]} scale={0.215} />
      <mesh geometry={nodes.ghiera_mi_basso_e_cantino.geometry} material={materials['metallo meccaniche']} position={[-0.025, -0.002, -0.402]} rotation={[-0.212, 0, 0.004]} scale={0.273} />
      <mesh geometry={nodes.ghiera_la_e_si.geometry} material={materials['metallo meccaniche']} position={[-0.023, -0.009, -0.436]} rotation={[-0.212, 0, -0.001]} scale={0.273} />
      <mesh geometry={nodes.ghiera_re_e_sol.geometry} material={materials['metallo meccaniche']} position={[-0.021, -0.017, -0.47]} rotation={[-0.213, 0, -0.001]} scale={0.273} />
      <mesh geometry={nodes.perno_re.geometry} material={materials['metallo meccaniche']} position={[-0.021, -0.011, -0.471]} rotation={[2.926, -1.28, 3.138]} />
      <mesh geometry={nodes.perno_la.geometry} material={materials['metallo meccaniche']} position={[-0.023, -0.004, -0.437]} rotation={[-0.213, 0.457, 0.001]} />
      <mesh geometry={nodes.perno_mi_basso.geometry} material={materials['metallo meccaniche']} position={[-0.025, 0.003, -0.403]} rotation={[-0.21, -0.946, 0.002]} />
      <mesh geometry={nodes.Plane001.geometry} material={materials['legno tastiera']} position={[0, 0.007, 0.057]} rotation={[0.009, 0, 0]} />
      <mesh geometry={nodes.Circle028.geometry} material={materials['madreperla tastini']} position={[-0.013, 0.008, -0.045]} rotation={[0.009, 0, 0]} />
      <mesh geometry={nodes.plancia.geometry} material={materials['plastica patella proteggicassa']} position={[0, 0.003, 0.145]} rotation={[0.009, -Math.PI / 2, 0]} scale={0.182} />
      <mesh geometry={nodes.ponte.geometry} material={materials['capotasto e ponticelli']} position={[0, 0.005, 0.29]} rotation={[0.009, 0.099, 0]} />
      <group position={[0.003, 0.002, -0.005]} rotation={[0.009, -1.57, 0]}>
        <mesh geometry={nodes.Plane027.geometry} material={materials['legno cassa sotto']} />
        <mesh geometry={nodes.Plane027_1.geometry} material={materials['legno cassa sopra']} />
      </group>
    </group>
  )
}

useGLTF.preload('/acoustic_guitar.glb')
