/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/acoustic_guitar.glb 
Author: pezcurrel (https://sketchfab.com/pezcurrel)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/acoustic-guitar-770b851ca34343a2825180ec23800402
Title: Acoustic guitar
*/

import React, { useRef } from 'react'
import { useGLTF, PositionalAudio } from '@react-three/drei'

export function Acoustic_guitar(props) {
  const { nodes, materials, scene } = useGLTF('/acoustic_guitar.glb')
  
  const sound = useRef()

  // Ensure textures use sRGB encoding
  useEffect(() => {
    Object.values(materials).forEach(mat => {
      if (mat.map) mat.map.encoding = THREE.sRGBEncoding;
    });
  }, [materials]);

  const playSound = () => {
    // Check if sound exists
    if (sound.current) {
        // Optional: Stop if already playing so you can spam-click it
        if (sound.current.isPlaying) sound.current.stop()
        
        // Play the sound!
        sound.current.play()
        
        // OPTIONAL: Add a little "wobble" animation or particle effect here later
    }
  }
  
  return (

    // <group {...props} dispose={null}>
    //   <PositionalAudio 
    //     ref={sound} 
    //     url="/Guitar_Twang.mp3" 
    //     distance={5} 
    //     loop={false}
    //   />

    //   {/* 2. Render the model exactly as it exists in the file */}
    //   <primitive 
    //     object={scene} 
    //     onClick={playSound}
    //     onPointerOver={() => document.body.style.cursor = 'pointer'}
    //     onPointerOut={() => document.body.style.cursor = 'auto'}
    //   />
    // </group>


    <group {...props} dispose={null}>

      {/* 2. The Invisible Speaker 
          url: Path to your mp3 in the public folder
          distance: How far (in units) the sound carries. 
                    10 means it gets quiet 10 units away.
      */}
      <PositionalAudio 
        ref={sound} 
        url="/Guitar_Twang.mp3" 
        distance={5} 
        loop={false}
      />

      <group rotation={[-Math.PI / 2, 0, 0]}
        onClick={playSound}
        onPointerOver={() => document.body.style.cursor = 'pointer'}
        onPointerOut={() => document.body.style.cursor = 'auto'}
      >
        <group position={[0, -0.001, 0.005]} rotation={[0.009, 0, -Math.PI / 2]}>
          <mesh geometry={nodes.cassa_0.geometry} material={materials.legno_cassa_sotto} />
          <mesh geometry={nodes.cassa_1.geometry} material={materials.legno_cassa_sopra} />
        </group>
        <group position={[0.004, 0.36, 0.013]} rotation={[0.009, 0, 0]}>
          <mesh geometry={nodes.corda_sol_0.geometry} material={materials.corde_zigrinate} />
          <mesh geometry={nodes.corda_sol_1.geometry} material={materials.corde_non_zigrinate} />
        </group>
        <group position={[-0.023, 0.437, -0.002]} rotation={[-0.212, 0, -0.685]}>
          <mesh geometry={nodes.corda_la_0.geometry} material={materials.corde_zigrinate} />
          <mesh geometry={nodes.corda_la_1.geometry} material={materials.corde_non_zigrinate} />
        </group>
        <group position={[-0.005, -0.291, 0.009]} rotation={[0.009, 0, 0]}>
          <mesh geometry={nodes.corda_re_0.geometry} material={materials.corde_zigrinate} />
          <mesh geometry={nodes.corda_re_1.geometry} material={materials.corde_non_zigrinate} />
        </group>
        <mesh geometry={nodes.plancia_0.geometry} material={materials.plastica_patella_proteggicassa} position={[0, -0.145, 0.003]} rotation={[0.009, 0, -Math.PI / 2]} scale={0.182} />
        <mesh geometry={nodes.Circle028_0.geometry} material={materials.madreperla_tastini} position={[-0.013, 0.045, 0.008]} rotation={[0.009, 0, 0]} />
        <mesh geometry={nodes.Plane001_0.geometry} material={materials.legno_tastiera} position={[0, -0.057, 0.007]} rotation={[0.009, 0, 0]} />
        <mesh geometry={nodes.perno_mi_basso_0.geometry} material={materials.metallo_meccaniche} position={[-0.025, 0.403, 0.003]} rotation={[-0.212, -0.001, -0.946]} />
        <mesh geometry={nodes.perno_la_0.geometry} material={materials.metallo_meccaniche} position={[-0.023, 0.437, -0.004]} rotation={[-0.212, -0.001, 0.457]} />
        <mesh geometry={nodes.perno_re_0.geometry} material={materials.metallo_meccaniche} position={[-0.021, 0.471, -0.011]} rotation={[-0.213, -0.001, -1.862]} />
        <mesh geometry={nodes.ghiera_re_e_sol_0.geometry} material={materials.metallo_meccaniche} position={[-0.021, 0.47, -0.017]} rotation={[-0.213, 0.001, 0]} scale={0.273} />
        <mesh geometry={nodes.ghiera_la_e_si_0.geometry} material={materials.metallo_meccaniche} position={[-0.023, 0.436, -0.009]} rotation={[-0.212, 0.001, 0]} scale={0.273} />
        <mesh geometry={nodes.ghiera_mi_basso_e_cantino_0.geometry} material={materials.metallo_meccaniche} position={[-0.025, 0.402, -0.002]} rotation={[-0.212, -0.004, 0]} scale={0.273} />
        <mesh geometry={nodes.Circle016_0.geometry} material={materials.metallo_meccaniche} position={[-0.021, 0.467, -0.033]} rotation={[2.931, -0.023, -3.041]} scale={0.215} />
        <mesh geometry={nodes.Circle015_0.geometry} material={materials.metallo_meccaniche} position={[-0.023, 0.432, -0.026]} rotation={[2.931, -0.023, -3.041]} scale={0.215} />
        <mesh geometry={nodes.Circle014_0.geometry} material={materials.metallo_meccaniche} position={[-0.025, 0.398, -0.018]} rotation={[2.931, -0.023, -3.041]} scale={0.215} />
        <mesh geometry={nodes.chiave_mi_basso_0.geometry} material={materials.metallo_meccaniche} position={[-0.045, 0.406, -0.022]} rotation={[0.651, -0.039, -0.053]} />
        <mesh geometry={nodes.chiave_la_0.geometry} material={materials.metallo_meccaniche} position={[-0.043, 0.44, -0.03]} rotation={[-0.729, 0.044, -0.049]} />
        <mesh geometry={nodes.chiave_re_0.geometry} material={materials.metallo_meccaniche} position={[-0.04, 0.474, -0.037]} rotation={[-0.994, 0.055, -0.035]} />
        <mesh geometry={nodes.Circle006_0.geometry} material={materials.metallo_meccaniche} position={[-0.025, 0.39, -0.018]} rotation={[2.929, 0, -0.565]} />
        <mesh geometry={nodes.Circle007_0.geometry} material={materials.metallo_meccaniche} position={[-0.024, 0.424, -0.025]} rotation={[2.929, 0, -1.158]} />
        <mesh geometry={nodes.Circle011_0.geometry} material={materials.metallo_meccaniche} position={[-0.022, 0.458, -0.033]} rotation={[2.929, 0, -0.686]} />
        <mesh geometry={nodes.manico_0.geometry} material={materials.legno_manico} position={[0, -0.001, 0.005]} rotation={[-1.561, 0, -Math.PI]} />
        <mesh geometry={nodes.Plane002_0.geometry} material={materials.frets} position={[0, 0.322, 0.01]} rotation={[1.58, -Math.PI / 2, 0]} scale={[1, 1, 1.001]} />
        <mesh geometry={nodes.Plane003_0.geometry} material={materials.frets} position={[0, 0.288, 0.01]} rotation={[1.58, -Math.PI / 2, 0]} scale={[1, 1, 1.001]} />
        <mesh geometry={nodes.Plane004_0.geometry} material={materials.frets} position={[0, 0.256, 0.009]} rotation={[1.58, -Math.PI / 2, 0]} scale={[1, 1, 1.001]} />
        <mesh geometry={nodes.Plane005_0.geometry} material={materials.frets} position={[0, 0.225, 0.009]} rotation={[1.58, -Math.PI / 2, 0]} scale={[1, 1, 1.001]} />
        <mesh geometry={nodes.Plane006_0.geometry} material={materials.frets} position={[0, 0.196, 0.009]} rotation={[1.58, -Math.PI / 2, 0]} scale={[1, 1, 1.001]} />
        <mesh geometry={nodes.Plane007_0.geometry} material={materials.frets} position={[0, 0.169, 0.009]} rotation={[1.58, -Math.PI / 2, 0]} scale={[1, 1, 1.001]} />
        <mesh geometry={nodes.Plane008_0.geometry} material={materials.frets} position={[0, 0.143, 0.008]} rotation={[1.58, -Math.PI / 2, 0]} scale={[1, 1, 1.001]} />
        <mesh geometry={nodes.Plane009_0.geometry} material={materials.frets} position={[0, 0.119, 0.008]} rotation={[1.58, -Math.PI / 2, 0]} scale={[1, 1, 1.001]} />
        <mesh geometry={nodes.Plane010_0.geometry} material={materials.frets} position={[0, 0.096, 0.008]} rotation={[1.58, -Math.PI / 2, 0]} scale={[1, 1, 1.001]} />
        <mesh geometry={nodes.Plane011_0.geometry} material={materials.frets} position={[0, 0.075, 0.008]} rotation={[1.58, -Math.PI / 2, 0]} scale={[1, 1, 1.001]} />
        <mesh geometry={nodes.Plane012_0.geometry} material={materials.frets} position={[0, 0.054, 0.008]} rotation={[1.58, -Math.PI / 2, 0]} scale={[1, 1, 1.001]} />
        <mesh geometry={nodes.Plane013_0.geometry} material={materials.frets} position={[0, 0.035, 0.007]} rotation={[1.58, -Math.PI / 2, 0]} scale={[1, 1, 1.001]} />
        <mesh geometry={nodes.ponte_0.geometry} material={materials.capotasto_e_ponticelli} position={[0, -0.29, 0.005]} rotation={[0.009, 0, 0.099]} />
        <mesh geometry={nodes.Plane014_0.geometry} material={materials.frets} position={[0, 0.018, 0.007]} rotation={[1.58, -Math.PI / 2, 0]} scale={[1, 1, 1.001]} />
        <mesh geometry={nodes.Plane015_0.geometry} material={materials.frets} position={[0, 0, 0.007]} rotation={[1.58, -Math.PI / 2, 0]} scale={[1, 1, 1.001]} />
        <mesh geometry={nodes.Plane016_0.geometry} material={materials.frets} position={[0, -0.015, 0.007]} rotation={[1.58, -Math.PI / 2, 0]} scale={[1, 1, 1.001]} />
        <mesh geometry={nodes.Plane017_0.geometry} material={materials.frets} position={[0, -0.03, 0.007]} rotation={[1.58, -Math.PI / 2, 0]} scale={[1, 1, 1.001]} />
        <mesh geometry={nodes.Plane018_0.geometry} material={materials.frets} position={[0, -0.044, 0.007]} rotation={[1.58, -Math.PI / 2, 0]} scale={[1, 1, 1.001]} />
        <mesh geometry={nodes.Plane019_0.geometry} material={materials.frets} position={[0, -0.058, 0.007]} rotation={[1.58, -Math.PI / 2, 0]} scale={[1, 1, 1.001]} />
        <mesh geometry={nodes.Plane020_0.geometry} material={materials.frets} position={[0, -0.07, 0.006]} rotation={[1.58, -Math.PI / 2, 0]} scale={[1, 1, 1.001]} />
        <mesh geometry={nodes.Plane021_0.geometry} material={materials.frets} position={[0, -0.083, 0.006]} rotation={[1.58, -Math.PI / 2, 0]} scale={[1, 1, 1.001]} />
        <mesh geometry={nodes.reggiponte_0.geometry} material={materials.legno_reggiponte} position={[0, -0.296, 0.002]} rotation={[0.009, 0, 0]} />
        <mesh geometry={nodes.pirioli_0.geometry} material={materials.pirioli_ponte} position={[-0.024, -0.306, 0.011]} rotation={[0.009, 0, -Math.PI]} />
        <mesh geometry={nodes.reggicinghia_0.geometry} material={materials.metallo_meccaniche} position={[0, 0.008, -0.099]} rotation={[0.009, 0, 0]} />
        <mesh geometry={nodes.vite_reggicinghia_0.geometry} material={materials.metallo_meccaniche} position={[0, 0.008, -0.099]} rotation={[-3.132, 0, 0]} />
        <mesh geometry={nodes.jack_0.geometry} material={materials.metallo_meccaniche} position={[0, -0.518, -0.05]} rotation={[1.58, 0, 0]} />
        <mesh geometry={nodes.perno_mi_cantino_0.geometry} material={materials.metallo_meccaniche} position={[0.025, 0.403, 0.001]} rotation={[-0.212, -0.001, 0.412]} />
        <mesh geometry={nodes.perno_si_0.geometry} material={materials.metallo_meccaniche} position={[0.023, 0.436, -0.006]} rotation={[-0.212, -0.001, 1.887]} />
        <mesh geometry={nodes.perno_sol_0.geometry} material={materials.metallo_meccaniche} position={[0.021, 0.471, -0.014]} rotation={[-0.213, -0.001, -0.452]} />
        <mesh geometry={nodes.chiave_mi_cantino_0.geometry} material={materials.metallo_meccaniche} position={[0.033, 0.405, -0.022]} rotation={[0.126, -0.008, -0.065]} />
        <mesh geometry={nodes.chiave_si_0.geometry} material={materials.metallo_meccaniche} position={[0.031, 0.439, -0.03]} rotation={[-0.537, 0.034, -0.056]} />
        <mesh geometry={nodes.chiave_sol_0.geometry} material={materials.metallo_meccaniche} position={[0.029, 0.474, -0.037]} rotation={[0.624, -0.038, -0.054]} />
        <mesh geometry={nodes.Circle020_0.geometry} material={materials.metallo_meccaniche} position={[0.025, 0.39, -0.018]} rotation={[2.929, 0, 0]} />
        <mesh geometry={nodes.Circle021_0.geometry} material={materials.metallo_meccaniche} position={[0.024, 0.424, -0.026]} rotation={[2.929, 0, -0.651]} />
        <mesh geometry={nodes.Circle022_0.geometry} material={materials.metallo_meccaniche} position={[0.022, 0.458, -0.033]} rotation={[2.929, 0, 0.248]} />
        <mesh geometry={nodes.corda_mi_basso_0.geometry} material={materials.corde_zigrinate} position={[-0.025, 0.403, 0.004]} rotation={[-0.212, 0, 0.813]} />
        <mesh geometry={nodes.ponticello_0.geometry} material={materials.capotasto_e_ponticelli} position={[0, 0.359, 0.008]} rotation={[0.009, 0, 0]} />
        <mesh geometry={nodes.corda_si_0.geometry} material={materials.corde_non_zigrinate} position={[0.012, 0.36, 0.013]} rotation={[0.009, 0, 0]} />
        <mesh geometry={nodes.corda_mi_cantino_0.geometry} material={materials.corde_non_zigrinate} position={[0.02, 0.36, 0.013]} rotation={[0.009, 0, 0]} />
        <mesh geometry={nodes.Circle023_0.geometry} material={materials.madreperla_tastini} position={[0, -0.007, 0.007]} rotation={[0.009, 0, 0]} />
        <mesh geometry={nodes.Circle029_0.geometry} material={materials.madreperla_tastini} position={[0, 0.107, 0.008]} rotation={[0.009, 0, 0]} />
        <mesh geometry={nodes.Circle030_0.geometry} material={materials.madreperla_tastini} position={[0, 0.156, 0.009]} rotation={[0.009, 0, 0]} />
        <mesh geometry={nodes.Circle031_0.geometry} material={materials.madreperla_tastini} position={[0, 0.21, 0.009]} rotation={[0.009, 0, 0]} />
      </group>
    </group>
  )
}

useGLTF.preload('/acoustic_guitar.glb')
