/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/generic_flush_mount_ceiling_lamps_type_b.glb 
Author: Mad_Lobster_Workshop (https://sketchfab.com/Mad_Lobster_Workshop)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/generic-flush-mount-ceiling-lamps-type-b-1ff0d7f889ed412da1f916ce95eb44b7
Title: Generic Flush Mount Ceiling Lamps Type B
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Ceiling_Lamp(props) {
  const { nodes, materials } = useGLTF('/generic_flush_mount_ceiling_lamps_type_b.glb')
  return (
    <group {...props} dispose={null}>
      {/* <mesh geometry={nodes.Object_4.geometry} material={materials.Generic_Flush_Mount_Ceiling_Lamp_Type_B_Design_01} position={[-2.078, 0, 0]} />
      <mesh geometry={nodes.Object_6.geometry} material={materials.Generic_Flush_Mount_Ceiling_Lamp_Type_B_Design_01} position={[0.781, 0, 0]} />
      <mesh geometry={nodes.Object_8.geometry} material={materials.Generic_Flush_Mount_Ceiling_Lamp_Type_B_Design_02} position={[-1.502, 0, 0]} />
      <mesh geometry={nodes.Object_10.geometry} material={materials.Generic_Flush_Mount_Ceiling_Lamp_Type_B_Design_03} position={[-0.922, 0, 0]} />
      <mesh geometry={nodes.Object_12.geometry} material={materials.Generic_Flush_Mount_Ceiling_Lamp_Type_B_Design_04} position={[-0.32, 0, 0]} />
      <mesh geometry={nodes.Object_14.geometry} material={materials.Generic_Flush_Mount_Ceiling_Lamp_Type_B_Design_05} position={[0.262, 0, 0]} />
      <mesh geometry={nodes.Object_16.geometry} material={materials.Generic_Flush_Mount_Ceiling_Lamp_Type_B_Design_02} position={[1.177, 0, 0]} /> */}
      <mesh geometry={nodes.Object_18.geometry} material={materials.Generic_Flush_Mount_Ceiling_Lamp_Type_B_Design_03} position={[1.551, 0, 0]} />
      {/* <mesh geometry={nodes.Object_20.geometry} material={materials.Generic_Flush_Mount_Ceiling_Lamp_Type_B_Design_04} position={[1.916, 0, 0]} />
      <mesh geometry={nodes.Object_22.geometry} material={materials.Generic_Flush_Mount_Ceiling_Lamp_Type_B_Design_05} position={[2.284, 0, 0]} /> */}
    </group>
  )
}

useGLTF.preload('/generic_flush_mount_ceiling_lamps_type_b.glb')
