/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/persian_nain_carpet.glb 
Author: mfb64 (https://sketchfab.com/mfb64)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/persian-nain-carpet-dc98944361654db191422c91e685371a
Title: Persian Nain Carpet
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Office_Rug(props) {
  const { nodes, materials } = useGLTF('/persian_nain_carpet.glb')
  return (
    <group {...props} dispose={null}>
      <group position={[-2.021, 0.001, -0.002]}>
        <mesh geometry={nodes.Object_6.geometry} material={materials['VELVET-GREEN__Budapest']} />
        <mesh geometry={nodes.Object_7.geometry} material={materials['VELVET-GREEN__Budapest']} />
        <mesh geometry={nodes.Object_8.geometry} material={materials['VELVET-GREEN__Budapest']} />
      </group>
      <group position={[2.044, 0, -0.009]}>
        <mesh geometry={nodes.Object_10.geometry} material={materials['VELVET-GREEN__Budapest']} />
        <mesh geometry={nodes.Object_11.geometry} material={materials['VELVET-GREEN__Budapest']} />
        <mesh geometry={nodes.Object_12.geometry} material={materials['VELVET-GREEN__Budapest']} />
      </group>
      <mesh geometry={nodes.Object_4.geometry} material={materials.carpet} />
    </group>
  )
}

useGLTF.preload('/persian_nain_carpet.glb')
